app:
  port: 8888
  host: ""
  env: dev
log:
  format: cmd
  debug: true
  director: /logs/
  caller: true
  level: debug

database:
  driver: mysql
  migrate: true
  # use dsn
  dsn: fortest:test@tcp(123.207.73.185:3307)/fortest?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms

redis:
  enable: true
  host: 123.207.73.185
  port: 16379
  password: DbinggoYjddb
  db: 0

es:
  enable: false
  username: ""
  password: ""
  address: "127.0.0.0:9200"
