app:
  port: 8080
  env: dev

database:
  driver: mysql
  migrate: true
  dsn: fortest:test@tcp(123.207.73.185:3307)/fortest?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms

redis:
  enable: true
  host: localhost
  port: 6379
  password: myredispassword
  db: 0
